sudo: required
services:
- docker
script:
- TAG_VER=$(git ls-remote --tags --refs git://github.com/micropython/micropython.git
  | awk -F/ '{ print $3 }' ) | sort -t v -V -k 2,2 | tail -n 1)
- curl -s https://hub.docker.com/v2/repositories/mitchins/micropython-linux/tags/
  | grep -q \"${TAG_VER}\" || docker build --build-arg TAG_VER=$TAG_VER -t $DOCKER_USERNAME/micropython-linux:$TRAVIS_BRANCH -t $DOCKER_USERNAME/micropython-linux:$TAG_VER
  .
after_success:
- echo "Our tag is ${TAG_VER}"
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- '[ -z "${TAG_VER}" ] && "Skip push as no tag" || docker push $DOCKER_USERNAME/micropython-linux:$TRAVIS_BRANCH'
- '[ -z "${TAG_VER}" ] && "Skip push as no tag" || docker push $DOCKER_USERNAME/micropython-linux:$TAG_VER'
notifications:
  email: false
